s3:
  bucket:
      name: miristudy3
      base-path: study/image/

spring:
  datasource:
    url: jdbc:postgresql://miristudy3.cgjoimlwfmu2.ap-northeast-2.rds.amazonaws.com/miristudy
  jpa:
    show-sql: true
#  session:
#    store-type: redis
#  redis:
#    host: localhost

server:
  port: 5000